title: Amal Biju
title : About me
description : Hi, I’m Amal Biju, a Mechanical Engineering student at the College of Engineering Perumon. I’m passionate about innovation, problem-solving, and exploring the intersection of technology and mechanical systems.

With a keen interest in programming and engineering, I’m currently working on projects like reducing water usage in agriculture through mechanical solutions. I thrive on tackling challenges that make a meaningful impact and enjoy applying technical skills to real-world problems.

Beyond academics, I’m eager to grow professionally, collaborate on exciting projects, and contribute to shaping a sustainable and efficient future through engineering.

Feel free to connect with me or explore my projects to learn more about my journey.
